import { MimeTypes } from '~/app/presentation/components/base-styled/types'

const FileExtensions = {
  aac: 'audio/aac',
  abw: 'application/x-abiword',
  ai: 'application/postscript',
  'arc/bin/dll': 'application/octet-stream',
  'asf/asx': 'video/x-ms-asf',
  avi: 'video/x-msvideo',
  mkv: 'video/x-matroska',
  azw: 'application/vnd.amazon.ebook',
  bz: 'application/x-bzip',
  bz2: 'application/x-bzip2',
  csh: 'application/x-csh',
  css: 'text/css',
  csv: 'text/csv',
  doc: 'application/msword',
  eot: 'application/vnd.ms-fontobject',
  epub: 'application/epub+zip',
  gif: 'image/gif',
  'htm/html': 'text/html',
  ico: 'image/x-icon',
  ics: 'text/calendar',
  jar: 'application/java-archive',
  'jpeg/jpg': 'image/jpeg',
  js: 'application/javascript',
  json: 'application/json',
  'mid/midi': 'audio/midi',
  mov: 'video/quicktime',
  'mp2/mp3': 'audio/mpeg',
  mp4: 'video/mp4',
  'mpa/mpe/mpeg': 'video/mpeg',
  mpkg: 'application/vnd.apple.installer+xml',
  odp: 'application/vnd.oasis.opendocument.presentation',
  ods: 'application/vnd.oasis.opendocument.spreadsheet',
  odt: 'application/vnd.oasis.opendocument.text',
  oga: 'audio/ogg',
  ogv: 'video/ogg',
  ogx: 'application/ogg',
  otf: 'font/otf',
  png: 'image/png',
  pdf: 'application/pdf',
  ppt: 'application/vnd.ms-powerpoint',
  rar: 'application/x-rar-compressed',
  rtf: 'application/rtf',
  sh: 'application/x-sh',
  svg: 'image/svg+xml',
  swf: 'application/x-shockwave-flash',
  tar: 'application/x-tar',
  'tif/tiff': 'image/tiff',
  ts: 'video/MP2T',
  ttf: 'font/ttf',
  txt: 'text/plain',
  vsd: 'application/vnd.visio',
  wav: 'audio/x-wav',
  weba: 'audio/webm',
  webm: 'video/webm',
  webp: 'image/webp',
  wmv: 'video/x-ms-wmv',
  woff: 'font/woff',
  woff2: 'font/woff2',
  xhtml: 'application/xhtml+xml',
  'xls/xlsx': 'application/vnd.ms-excel',
  xlsx_OLD: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  xml: 'application/xml',
  xul: 'application/vnd.mozilla.xul+xml',
  zip: 'application/zip',
  '3gp': 'video/3gpp',
  '3gp (audio)': 'audio/3gpp',
  '3gp2': 'video/3gpp2',
  '3gp2 (audio)': 'audio/3gpp2',
  '7z': 'application/x-7z-compressed'
}

export const getMimeExtension = (type: MimeTypes) => FileExtensions[type]
